---
title: "MCC Novelty Kids"
author: "Manuel Bohn"
date: "23 7 2018"
output: html_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = FALSE)
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)


## importing data

d_new <- read_csv(file="../data/kids_novel.data.csv")%>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"))

d_old <- read_csv(file="../data/kids_novel.data.round1.csv")%>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"))

# check if someone needs to be excluded because wrong in training
# no one
d_new %>%
  filter(trial_type == "train") %>%
  group_by(subid)%>%
  summarise(correct = mean(correct)) %>%
  filter(correct == 0)


d_old %>%
  filter(trial_type == "train") %>%
  group_by(subid)%>%
  summarise(correct = mean(correct)) %>%
  filter(correct == 0)

d <- bind_rows(d_new,d_old)

```

# Subjects



## Overall



```{r sanity checks, echo = FALSE,warning = FALSE, message = FALSE}


## sanity checks
d %>%
  group_by(condition,trial_type) %>%
  summarise(n = length(unique(subid)), 
            correct = mean(correct)) %>%
  knitr::kable(digits = 2)


```

## By age bin


```{r kids per age group,echo = FALSE}

d %>%
  group_by(condition,age)%>%
  summarise(n = length(unique(subid)),
            age_num = mean(age_num))%>%
  knitr::kable(digits = 2)
```

# Plots

## Plot across age bins

```{r plot across age}
p3 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition,change, subid) %>%
  summarise(correct = mean(correct)) 

p4 <- p3 %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p3, aes(x = change, y = correct, col = change, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p4, aes(x = change, y = mean, col = change, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  facet_grid(condition ~.)+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Plot by age bin


```{r plot by age}
p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition,change,age, subid) %>%
  summarise(correct = mean(correct)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = change, y = correct, col = change, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = change, y = mean, col = change, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(condition~age)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c(F, T),
                     labels=c("No", "Yes"))
```

## Plot with age as continuous variable

```{r plot by numerical age}
p5 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition,change,age_num, subid) %>%
  summarise(correct = mean(correct)) 

ggplot(data = p5, aes(x = age_num, y = correct, col = change)) +
  geom_smooth(method = "lm", se = T)+
  geom_jitter( alpha = .5, height = 0.04)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
   facet_grid(condition ~.)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  #theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c(F, T),
                     labels=c("No", "Yes"))
```

# Inference

## T-tests against chance across age bins
```{r}
## t tests against chance
d %>%
  filter(trial_type == "test") %>%
  group_by(change, subid) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = list(correct)) %>%
  group_by(change) %>%
  mutate(df= t.test(unlist(correct), mu = 0.5)$parameter,
         t_value = t.test(unlist(correct), mu = 0.5)$statistic,
         p_value = t.test(unlist(correct), mu = 0.5)$p.value) %>%
  select(change,df,t_value,p_value) %>%
  knitr::kable(digits = 3)
 
```

## T-tests against chance per age bin
```{r}
## t tests against chance
d %>%
  filter(trial_type == "test") %>%
  group_by(age,change, subid) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = list(correct)) %>%
  group_by(age,change) %>%
  mutate(df= t.test(unlist(correct), mu = 0.5)$parameter,
         t_value = t.test(unlist(correct), mu = 0.5)$statistic,
         p_value = t.test(unlist(correct), mu = 0.5)$p.value) %>%
  select(age,change,df,t_value,p_value) %>%
  knitr::kable(digits = 3)
 
```

## GLMM



```{r}
## model
library(lme4)

lm_data <- d%>%
  filter(trial_type == "test")%>%
  mutate(choiceAgent = ifelse( change == "false", agent, altAgent),
         age_num = scale(age_num, center = TRUE, scale = TRUE))

# maximal converging model
lm <- glmer(correct ~ age_num * change + (change | subid) + (age_num * change | choiceAgent), 
              data = lm_data, family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(lm)

```

# Additional plots

To check for trial and item effects.

## Conditions by trial
```{r plot trials}
ms <- d %>%
  filter(trial_type == "test") %>%
  group_by(change, trial, subid) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, 
       aes(x = trial, y = mean, col = change)) +
  geom_line(aes(group= change)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_hline(yintercept = 0.5, lty=2)+
  theme_few() + 
  scale_colour_solarized()
```

## By agent
```{r plot agents}
ms <- d %>%
  filter(trial_type == "test") %>%
  mutate(choiceAgent = ifelse( change == "false", agent, altAgent)) %>%
  group_by(change, choiceAgent, subid) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, 
       aes(x = choiceAgent, y = mean, col = change)) +
  geom_line(aes(group= change)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_hline(yintercept = 0.5, lty=2)+
  theme_few() + 
  scale_colour_solarized()
```





