---
title: "MCC Preference Kids - Replication"
author: "Manuel Bohn"
output: html_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = FALSE)

###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)


## importing data
files <- dir("~/Work/MCC/git-mcc/kids_pref_data_2/")

 raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/MCC/git-mcc/kids_pref_data_2/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,45,str_length(jf)-11)
  id <- as_data_frame(jd$data$data) %>% mutate(test_date = date)
  raw_data <- bind_rows(raw_data, id)
}


length(unique(raw_data$subid))

d_raw <-raw_data %>%
  mutate(test_date = as.Date(test_date),
         experiment = "mcc_kids_pref_2")

log <- read_excel("../../../MCC-subject_log.xlsx", 1)%>%
  filter(Condition == "pref2")%>%
  select(subid,experimenter,keep_drop,sex,dob)

length(unique(log$subid))


sum(log$keep_drop=="drop")

d <- left_join(d_raw,log, by = "subid")%>%
  filter(keep_drop == "keep")%>%
  mutate(dob = as.numeric(dob),
         dob = as.Date(dob,origin = "1899-12-30"),
         age_num = lubridate::time_length(difftime(test_date,dob), "years"),
         check_age = ifelse(substr(age_num,1,1) == subage, T, F))

length(unique(d$subid))

#write_csv(d, "../data/kids_pref_2_data.csv")

```

# Sample size per age bin

```{r kids per age group,echo = F }

d %>%
  group_by(subage)%>%
  summarise(n = length(unique(subid)))%>%
  knitr::kable(digits = 2)
```

# Plots

## Plot across age bins

```{r plot across age,echo = F}
p3 <- d %>%
  filter(trial != "train") %>%
  group_by(speakerChange,subid) %>%
  summarise(correct = mean(correct)) 

p4 <- p3 %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p3, aes(x = speakerChange, y = correct, col = speakerChange, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p4, aes(x = speakerChange, y = mean, col = speakerChange, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("Same Speaker", "Different Speaker"))
```


## Plot by age bin

```{r plot by age,echo = F}
p1 <- d %>%
  filter(trial != "train") %>%
  group_by(speakerChange,subage, subid) %>%
  summarise(correct = mean(correct)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = speakerChange, y = correct, col = speakerChange, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = speakerChange, y = mean, col = speakerChange, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("Same Speaker", "Different Speaker"))
```

## Plot with age as continuous variable

```{r plot by numerical age,echo = F}
p5 <- d %>%
  filter(trial != "train") %>%
  group_by(speakerChange,age_num, subid) %>%
  summarise(correct = mean(correct)) 

ggplot(data = p5, aes(x = age_num, y = correct, col = speakerChange)) +
  geom_smooth(method = "lm", se = T)+
  geom_jitter( alpha = .5, height = 0.04)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  #theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("Same Speaker", "Different Speaker"))
```

# Inference

## T-tests against chance per age bin
```{r,echo = F}
## t tests against chance
d %>%
  filter(trial != "train") %>%
  group_by(subage,speakerChange, subid) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = list(correct)) %>%
  group_by(subage,speakerChange) %>%
  mutate(df= t.test(unlist(correct), mu = 0.5)$parameter,
         t_value = t.test(unlist(correct), mu = 0.5)$statistic,
         p_value = t.test(unlist(correct), mu = 0.5)$p.value) %>%
  select(subage,speakerChange,df,t_value,p_value) %>%
  knitr::kable(digits = 3)
 
```

## GLMM

```{r, warning= F, message=F, }
## model
library(lme4)

lm_data <- d%>%
  filter(trial != "train")%>%
  mutate(choiceAgent = ifelse( speakerChange == "false", agent, altAgent),
         age_num = scale(age_num, center = TRUE, scale = TRUE))

# maximal converging model
lm <- glmer(correct ~ age_num * speakerChange + (speakerChange | subid) + (age_num * speakerChange | choiceAgent), 
              data = lm_data, family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(lm)

```

# Joining round 1 and round 2

```{r,include= F}


d1 <- read_csv(file="../data/kids_pref_data.csv")%>%
  filter(age != "2")%>%
  mutate(speakerChange = ifelse(change == F, "false", "true"),
         subage = as.character(age))

d_sum <- bind_rows(d,d1)%>%
    filter(trial != "train")
  
```
## sample size
```{r,echo = F}
d_sum %>%
  group_by(subage)%>%
  summarise(n = length(unique(subid)))%>%
  knitr::kable(digits = 2)
```

## Plot by age bin

```{r plot by age sum ,echo = F}
p_sum1 <- d_sum %>%
  filter(trial != "train") %>%
  group_by(speakerChange,subage, subid) %>%
  summarise(correct = mean(correct)) 

p_sum2 <- p_sum1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p_sum1, aes(x = speakerChange, y = correct, col = speakerChange, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p_sum2, aes(x = speakerChange, y = mean, col = speakerChange, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("Same Speaker", "Different Speaker"))
```

## Plot with age as continuous variable

```{r plot by numerical age sum ,echo = F}
p_sum3 <- d_sum %>%
  filter(trial != "train") %>%
  group_by(speakerChange,age_num, subid) %>%
  summarise(correct = mean(correct)) 

ggplot(data = p_sum3, aes(x = age_num, y = correct, col = speakerChange)) +
  geom_smooth(method = "lm", se = T)+
  geom_jitter( alpha = .5, height = 0.04)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  #theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("Same Speaker", "Different Speaker"))
```
## GLMM

```{r, warning=F,message=F}
## model
library(lme4)

lm_sum_data <- d_sum%>%
  filter(trial != "train")%>%
  mutate(choiceAgent = ifelse( speakerChange == "false", agent, altAgent),
         age_num = scale(age_num, center = TRUE, scale = TRUE))

# maximal converging model
lm_sum <- glmer(correct ~ age_num * speakerChange + (speakerChange | subid) + (age_num * speakerChange | choiceAgent), 
              data = lm_sum_data, family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(lm_sum)

```
