---
title: "MCC Simulations"
author: "Manuel Bohn"
date: "10 2 2018"
output: html_document
---

```{r setup}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(ggpubr)
library(lme4)

```


```{r}
conditions <- read.csv("condition_means.csv", sep=";")


generate_data <- function(condition_df, n_subs = 40, n_trials = 3) {
  tibble(count = condition_df$count,
         speaker = condition_df$speaker, 
         prior = condition_df$prior,
         info = condition_df$info, 
         experiment = condition_df$experiment,
         correct = rbinom( n_subs * n_trials, 1,
                          condition_df$correct_add),
         correct2 = rbinom( n_subs * n_trials, 1,
                          condition_df$correct_cg),
         correct3 = rbinom( n_subs * n_trials, 1,
                          condition_df$correct_inf),
         correct4 = rbinom( n_subs * n_trials, 1,
                          condition_df$correct_seq),
         subid = rep(1:n_subs, n_trials))
}

participant_data <- conditions %>%
  mutate(index = 1:n()) %>%
  split(.$index) %>%
  map_df(generate_data) %>%
  mutate(subid=paste(subid,speaker,prior,info,sep=""))%>%
  mutate(prior = relevel(prior, ref="cntl"),
         info = relevel(info, ref="neutral"))
  
  #mutate(correct=correct+rnorm(n=length(subid), mean=0, sd=0.05*(as.numeric(as.factor(subid)))/length(subid)))%>%
  #mutate(correct = ifelse(correct < 0.5, 0,1))
  
```

```{r}

library('grid')

ms <- participant_data %>%
  group_by(count,experiment,speaker, prior, info) %>%
  summarise(correct = mean(correct),
            correct2 = mean(correct2),
            correct3 = mean(correct3),
            correct4 = mean(correct4))

mp <- ggplot(ms, 
       aes(x = prior, y = correct, fill = prior)) +
  geom_bar(stat="identity") + 
  facet_grid(~speaker*info,scales = "free_x", space = "free_x")+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  theme_few(base_size = 6) + 
  ylim(0,1)+
  ggtitle("1: mean(info+prior)")+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())

cgp <- ggplot(ms, 
       aes(x = prior, y = correct2, fill = prior)) +
  geom_bar(stat="identity") + 
  facet_grid(~speaker*info,scales = "free_x", space = "free_x")+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  theme_few(base_size = 6) + 
  ylim(0,1)+
  ggtitle("2: prior > info")+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())

ip <- ggplot(ms, 
       aes(x = prior, y = correct3, fill = prior)) +
  geom_bar(stat="identity") + 
  facet_grid(~speaker*info,scales = "free_x", space = "free_x")+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  theme_few(base_size = 6) + 
  ylim(0,1)+
  ggtitle("3: info > prior")+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())

seq <- ggplot(ms, 
       aes(x = prior, y = correct4, fill = prior)) +
  geom_bar(stat="identity") + 
  facet_grid(~speaker*info, scales = "free_x", space = "free_x")+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  theme_few(base_size = 6) + 
  ylim(0,1)+
  ggtitle("4: if (info = prior, max(prior,info), mean(prior,info)")+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())

sum= ggarrange(mp, cgp,ip,seq,
          ncol = 1, nrow = 4,
          common.legend=TRUE)
```
```{r fig3, fig.asp = 1.2}
sum
```



```{r}

## Sometimes models for different predictions (correct - correct4) do not converge - probably due to data structure, as this changes when data are newly simulated.

lm <- glmer(correct3 ~ speaker * prior * info+ (1|subid), 
      data = participant_data,
      family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(lm)
drop1(lm, test = "Chisq")


```

