---
title: "MCC Informativeness - Pilot with Kids"
author: "Manuel Bohn"
output: html_document
---

```{r setup, include = F}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)

## importing data
files <- dir("~/Work/MCC/git-mcc/kids_info_pilot/trees")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/MCC/git-mcc/kids_info_pilot/trees/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$data$data)
  raw_data <- bind_rows(raw_data, id)
}

d_trees <- raw_data %>%
  filter(trial != "train1",
         trial != "train2",
         trial != "filler1",
         trial != "filler2",
         subage != "Test")


files <- dir("~/Work/MCC/git-mcc/kids_info_pilot/robots_point_4_map")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/MCC/git-mcc/kids_info_pilot/robots_point_4_map/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$data$data)
  raw_data <- bind_rows(raw_data, id)
}

d_robots <- raw_data %>%
  filter(trial != "train1",
         trial != "train2",
         trial != "filler1",
         trial != "filler2",
         subage != "Test")



files <- dir("~/Work/MCC/git-mcc/kids_info_pilot/trees_left_right")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/MCC/git-mcc/kids_info_pilot/trees_left_right/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  id <- as_data_frame(jd$data$data)
  raw_data <- bind_rows(raw_data, id)
}

d_trees_left_right <- raw_data %>%
  filter(trial != "train1",
         trial != "train2",
         trial != "filler1",
         trial != "filler2",
         subage != "Test")
```

# Sample

## Trees

```{r sample trees, echo = F}

d_trees %>%
  group_by(subage) %>%
  summarise(n = length(unique(subid))) %>%
  knitr::kable(digits = 3)
```

## Robots


```{r sample robots, echo = F}

d_robots %>%
  group_by(subage) %>%
  summarise(n = length(unique(subid))) %>%
  knitr::kable(digits = 3)
```

## Trees left right

```{r sample trees left right, echo = F}
d_trees_left_right %>%
  group_by(subage) %>%
  summarise(n = length(unique(subid))) %>%
  knitr::kable(digits = 3)
```


# Results overall

## Trees

Experiment: [Tree Setup](https://langcog.stanford.edu/expts/cue/exp/kids/kids_cue_barrier7_tree.html)

```{r , echo = F}

p <- d_trees %>%
  group_by(control,subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = control, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = control, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Robots

Experiment: [Robot Setup](https://langcog.stanford.edu/expts/cue/exp/kids/kids_cue_barrier6.html)

```{r, echo = F}

p <- d_robots %>%
  group_by(control,subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = control, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = control, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Trees left right

Experiment: [Trees with objects left and right](https://langcog.stanford.edu/expts/cue/exp/kids/kids_cue_barrier8_tree_left_right.html)

```{r, echo = F}

p <- d_trees_left_right %>%
  group_by(control,subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = control, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = control, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```



# Results by age

## Trees

```{r , echo = F}

p <- d_trees %>%
  group_by( subage, control, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Robots

```{r , echo = F}

p <- d_robots %>%
  group_by( subage, control, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Trees left right

```{r , echo = F}

p <- d_trees_left_right %>%
  group_by( subage, control, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = control, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = control, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

# Positioning bias (top vs. bottom object more informative)

## Trees
```{r , echo = F}

p <- d_trees %>%
  group_by( subage, targetPosition, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = targetPosition, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = targetPosition, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Robots

```{r , echo = F}

p <- d_robots %>%
  group_by( subage, targetPosition, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = targetPosition, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = targetPosition, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

## Trees left right (here it is inner vs outer object)

```{r , echo = F}

p <- d_trees_left_right %>%
  group_by( subage, targetPosition, subid) %>%
  summarise(correct = mean(correct)) 

p1 <- p %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p, aes(x = targetPosition, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p1, aes(x = targetPosition, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```



```{r}
# power analysis for cue barrier

xx <- bind_rows(d_trees,
d_trees_left_right,
d_robots)%>%
  filter(subage != "2")


 power_data <- xx %>%
  group_by(subage,subid) %>%
  summarise(correct = mean(correct)) 
 
 
library("lsr")
 
library("pwr")
 
d_robots %>%
  group_by(subage, subid) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = list(correct)) %>%
  group_by(subage) %>%
  mutate(mean = mean(unlist(correct)),
        df= t.test(unlist(correct), mu = 0.5)$parameter,
         t_value = t.test(unlist(correct), mu = 0.5)$statistic,
         p_value = t.test(unlist(correct), mu = 0.5)$p.value,
        d = cohensD(unlist(correct), mu = 0.5)) %>%
  select(subage,mean,df,t_value,p_value,d) %>%
  knitr::kable(digits = 3)


cohensD(power_data$correct,mu = 0.5)

pwr.t.test(d = 0.65, power = 0.8, type = "one.sample")

pwr.t.test(d = 0.8, power = 0.8, type = "one.sample")

pwr.t.test(d = 1.05, power = 0.8, type = "one.sample")



```

