---
title: "MCC Informativeness Kids 2"
author: "Manuel Bohn"
output: html_document
---

```{r import data, include = F}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)

## importing data
files <- dir("~/Work/MCC/git-mcc/kids_info_data/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/MCC/git-mcc/kids_info_data/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,45,str_length(jf)-11)
  id <- as_data_frame(jd$data$data) %>% mutate(test_date = date)
  raw_data <- bind_rows(raw_data, id)
}

d_raw <-raw_data %>%
  mutate(test_date= ifelse(test_date == "18-10-10", paste(20,test_date,sep = ""),test_date),
         subid= ifelse(subid == "101018_8_inf", "181010_8_inf",subid),
         subid= ifelse(subid == "181031_3", "181031_3_inf",subid),
         test_date= ifelse(test_date == "18-XX-XX", "2018-10-10",test_date),
         experiment = "mcc_kids_inf_2")

log <- read_excel("../../MCC-subject_log.xlsx", 1)%>%
  filter(Condition == "inf")%>%
  select(subid,experimenter,keep_drop,sex,dob)

d <- left_join(d_raw,log, by = "subid")%>%
  filter(keep_drop == "keep")%>%
  mutate(dob = as.numeric(dob),
         dob = as.Date(dob,origin = "1899-12-30"),
         age_num = lubridate::time_length(difftime(test_date,dob), "years"),
         check_age = ifelse(substr(age_num,1,1) == subage, T, F))

```

# Sample size per age bin

```{r kids per age group,echo = F }

d %>%
  group_by(subage)%>%
  summarise(n = length(unique(subid)))%>%
  knitr::kable(digits = 2)

```

# Plot filler by age

```{r plot by age, echo= FALSE}
pf1 <- d %>%
      filter(trial == "filler1" | trial == "filler2")%>%
  group_by(control,subage, subid) %>%
  summarise(correct = mean(correct)) 

pf2 <- pf1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = pf1, aes(x = control, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = pf2, aes(x = control, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```



# Plot by age group

```{r plot by age, echo= FALSE}

p1 <- d %>%
  filter(trial != "filler1",
         trial != "filler2")%>%
  group_by(control,subage, subid) %>%
  summarise(correct = mean(correct)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = control, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = control, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  facet_wrap(~subage)+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

# Performance by trial
```{r plot trials}
ms <- d %>%
  filter(trial != "filler1",
         trial != "filler2") %>%
  group_by(subage, trial, subid) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, 
       aes(x = trial, y = mean, col = subage)) +
  geom_line(aes(group= subage)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_hline(yintercept = 0.5, lty=2)+
  theme_few() + 
  scale_colour_solarized()
```



## Plot with age as continuous variable

```{r plot by numerical age}
p5 <- d %>%
  filter(trial != "filler1",
         trial != "filler2") %>%
  group_by(age_num, subid) %>%
  summarise(correct = mean(correct)) 

ggplot(data = p5, aes(x = age_num, y = correct)) +
  geom_smooth(method = "loess", se = T)+
  geom_jitter( alpha = .5, height = 0.04)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  #theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```



# Plot overall test

```{r plot across age, echo = F }
p3 <- d %>%
  filter(trial != "filler1",
  trial != "filler2")%>%
  group_by(control, subid) %>%
  summarise(correct = mean(correct)) 

p4 <- p3 %>%
  multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = p3, aes(x = control, y = correct, col = control, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p4, aes(x = control, y = mean, col = control, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Control",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))

```




