---
title: "MCC Visualizations"
author: "Manuel Bohn"
date: "23 10 2018"
output: html_document
---

```{r setup, include=FALSE}
load("mcc_model_comparison.RData")

library(tidyverse)
library(knitr)
library(ggthemes)
library(langcog)
library(rwebppl)
library(matrixStats)
library(coda)
library(ggpubr)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```

```{r}
# data ex 1 and ex 2 adults

d1 <- bind_rows(read_csv(file="novel.data.csv"),
               read_csv(file="pref.data.csv")) %>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"),
         control = ifelse(change == "true", "true" , "false"))

d2 <- read_csv(file="inf.data.csv") %>%
  mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"))

d <- bind_rows(d1,d2) %>%
  mutate(condition = ifelse(condition == "preference", 2, ifelse(condition == "novelty", 3,1)))


```

```{r}
# plot ex 1 and 2 adults

## pointrange plot
p1 <- d %>%
  filter(trial_type == "test") %>%
  mutate(control = ifelse(control == "true", "Control", "Test")) %>%
  group_by(condition ,control, id) %>%
  summarise(correct = mean(correct))

p2 <- p1 %>%
  multi_boot_standard(col = "correct") %>%
  ungroup()%>%
  mutate(condition = as.character(condition))


exp1 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "1"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "1"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "1"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#657b83","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),
        panel.border = element_rect(color = "#dc322f", fill = NA, size = 6))


exp2 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "2"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "2"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "2"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
       axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))


exp3 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "3"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "3"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "3"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))


exp12 <- ggplot() +
  geom_rect(data = p2, aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1, aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#657b83","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))



```


```{r}
ggsave("graphs/ex1_2.png", width = 6.5, height = 2, scale = 1.8)
```



```{r}
# barplots
p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition ,control, id) %>%
  summarise(correct = mean(correct))  %>%
  multi_boot_standard(col = "correct")

ggplot(p1, 
       aes(x = control, y = mean, fill = control)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x="",y="Proportion Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Info."))) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_fill_solarized(name="Condition",
                     breaks=c("false", "true"),
                     labels=c("Test", "Control"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())


```

```{r}
ggsave("graphs/ex1_2.png", width = 6.5, height = 2, scale = 1.5)
```







```{r}
## kids preference data

d_ipad <- read_csv(file="kids_pref.data.csv")

d_hand_code <- read.csv(file="kids_pref_handcoding.data.csv", sep = ";")%>%
  mutate(age_num = as.numeric(as.character(age_num)))

d <- bind_rows(d_ipad,d_hand_code)%>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"))%>%
  filter(subid != "200718_8_pref")


# check if someone needs to be excluded because wrong in training
# no one
d %>%
  filter(trial_type == "train") %>%
  group_by(subid)%>%
  summarise(correct = mean(correct)) %>%
  filter(correct == 0)
```

```{r}
# kids pref plot

p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(change,age, subid) %>%
  summarise(correct = mean(correct))%>%
  multi_boot_standard(col = "correct")


ggplot(p1, 
       aes(x = change, y = mean, fill = change)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x="",y="Proportion Expected Choice")+
  facet_wrap( ~ age, labeller = as_labeller(c(`2`="2-year-olds", `3`="3-year-olds", `4`="4-year-olds"))) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_fill_solarized(name="Condition",
                     breaks=c("false", "true"),
                     labels=c("Test", "Control"))





## pointrange plot
p1 <- d %>%
  filter(trial_type == "test") %>%
  mutate(change = ifelse(change == "true", "Control", "Test")) %>%
  group_by(age ,change, subid) %>%
  summarise(correct = mean(correct))

p2 <- p1 %>%
  multi_boot_standard(col = "correct") %>%
  ungroup()%>%
  mutate(age = as.character(age))

exp2k <- ggplot() +
  geom_rect(data = p2, aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1, aes(x = change, y = correct, col = change), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = change, y = mean,ymin = ci_lower, ymax = ci_upper, col = change),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ age, labeller = as_labeller(c(`2`="2-year-olds", `3`="3-year-olds", `4`="4-year-olds"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#268bd2","#268bd2","#268bd2"))+
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))



```


```{r}
ggarrange(exp12, exp2k, ncol = 1, nrow = 2, legend = "bottom", common.legend = T)
```



```{r}
ggsave("graphs/ex12_kids.pdf", width = 6.5, height = 4, scale = 1.5)
```




```{r}
# data ex 3 first round

dat <- bind_rows(read_csv(file="ex3.novel.data.csv"),
               read_csv(file="ex3.pref.data.csv")) %>%
  mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"))

dat %>%
  filter(alignment == "incongruent") %>%
  filter(correct_inf == correct_prior)


# check if someone needs to be excluded because wrong in training
# no one, that's good
dat %>%
  filter(trial_type == "train") %>%
  group_by(id)%>%
  summarise(correct_inf = mean(correct_inf)) %>%
  filter(correct_inf == 0)
  
# check if someone did both experiments
# yes, two people
x <- dat %>%
  filter(trial_type == "train") %>%
  group_by(id)%>%
  summarise(n = length(correct_inf)) %>%
  filter(n > 2)

# exclude those who did both experiments
data <- dat %>%
  filter(!id %in% x$id) %>%
  filter(trial_type != "train") %>%
  mutate(Change = ifelse(change =="same", "Same speaker", "Different speaker"),
         Alignment = ifelse(alignment == "congruent", "Congruent", "Incongruent"),
         Experiment = ifelse(experiment == "pref_inf", "Preference", "Novelty"))


data %>%
  group_by(experiment,alignment,change) %>%
  summarise(n = length(id))


```


```{r}
# plot data Ex3 first round

p1 <- data %>%
  filter(trial_type == "test") %>%
  group_by(Experiment,Change ,Alignment, id) %>%
  summarise(correct = mean(correct_inf)) %>%
  multi_boot_standard(col = "correct")

ggplot(p1, 
       aes(x = Change, y = mean, fill = Alignment)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x=" ",y="Proportion Choosing More Informative")+
  facet_grid( ~ Experiment)+
  theme_few(base_size = 12) + 
  scale_fill_brewer(type = "qual")+
  theme(axis.text.x=element_text(angle = 0, vjust = 0.5, hjust = 0.5))+
  ylim(0,1)



## pointrange plot
p1 <- data %>%
  filter(trial_type == "test") %>%
  group_by(Experiment,Change ,Alignment, id) %>%
  summarise(correct = mean(correct_inf))

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_rect(data = p2, aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1, aes(x = Alignment, y = correct), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = Alignment, y = mean,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Choosing More Informative")+
  facet_grid ( ~ Experiment + Change) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F, col = F)+ 
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#859900","#859900","#859900"))+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1),
        panel.border = element_rect(color = "#859900", fill = NA, size = 6))

```



```{r}
ggsave("graphs/data_ex3_round1.pdf", width = 6.5, height = 3, scale = 1.8)
```




```{r}
## correlation round 1

pc1 <- plot.model%>%
  filter(Model == "Noisy RSA Model")%>%
  mutate(Prior = "Strong")
  
c1 <-ggplot(data = pc1,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = 1)+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = 1)+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = 1)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  ggtitle("Experiment 3")+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.9, aes(x = mean, y = Data), inherit.aes = F, size = 6)+
  #geom_smooth(method = "lm", se = F, col = "black", size =1)+
  theme_few(base_size = 20) + 
  guides(col = F)+
  scale_colour_viridis_d()
```

```{r}
ggsave("graphs/model_critique_ex3_round1.png", width = 4, height = 4, scale = 1)
```



```{r}
## correlation round 2

pc2 <- pred.ex3%>%
  filter(Model == "Noisy RSA Model")

c2 <- ggplot(data = pc2,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = 1)+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = 1 )+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = 1)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  ggtitle("Replication/Extension")+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.9, aes(x = mean, y = Data), inherit.aes = F, size = 6)+
  #geom_smooth(method = "lm", se = F, col = "black", size =0.4)+
  theme_few(base_size = 20) + 
  scale_colour_manual(values = rev(viridis::viridis(3)))
```

```{r}
ggarrange(c1, c2, ncol = 2, nrow = 1, legend = "right", common.legend = T)
```



```{r}
ggsave("graphs/model_critique_ex3_round1_2.pdf", width = 10, height = 4, scale = 1.2)
```
