---
title: "MCC Ex 1 and 2 overview"
author: "Manuel Bohn"
date: "9 4 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(ggthemes)
library(langcog)
```


```{r data}
d1 <- bind_rows(read_csv(file="novel.data.csv"),
               read_csv(file="pref.data.csv")) %>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"),
         control = ifelse(change == "true", "true" , "false"))

d2 <- read_csv(file="inf.data.csv") %>%
  mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"))

d <- bind_rows(d1,d2) %>%
  mutate(condition = ifelse(condition == "preference", 2, ifelse(condition == "novelty", 3,1)))


```

```{r plot data}

p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition ,control, id) %>%
  summarise(correct = mean(correct)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Info."))) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_colour_solarized(name="Condition",
                     breaks=c("false", "true"),
                     labels=c("Test", "Control"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())


```
