---
title: "MCC_Preference_Weak"
author: "Manuel Bohn"
date: "26 4 2018"
output: html_document
---

```{r setup}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)


## importing data
d <- read_csv(file="pref.weak.data2.csv") %>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"))

```

Sanity checks.
```{r sanity checks}

## sanity checks
d %>%
  group_by(trial_type) %>%
  summarise(n = length(unique(id)), 
            correct = mean(correct)) %>%
  knitr::kable(digits = 2)


# check if someone needs to be excluded because wrong in training
# no one
d %>%
  filter(trial_type == "train") %>%
  group_by(id)%>%
  summarise(correct = mean(correct)) %>%
  filter(correct == 0)

```

Plot for speaker change with 95%CI
```{r plot}

p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(change, id) %>%
  summarise(correct = mean(correct)) 

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p1, aes(x = change, y = correct, col = change, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = change, y = mean, col = change, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized(name="Speaker Change",
                     breaks=c("false", "true"),
                     labels=c("No", "Yes"))
```

T-tests against chance for each speaker change conditions
```{r}
## t tests against chance
d %>%
  filter(trial_type == "test") %>%
  group_by(change, id) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = list(correct)) %>%
  group_by(change) %>%
  mutate(df= t.test(unlist(correct), mu = 0.5)$parameter,
         t_value = t.test(unlist(correct), mu = 0.5)$statistic,
         p_value = t.test(unlist(correct), mu = 0.5)$p.value) %>%
  select(change,df,t_value,p_value) %>%
  knitr::kable(digits = 2)
 
```

ChoiceAgent can be seen as an approximation for "item".

```{r}
## model
library(lme4)

data_cg <- d%>%
  filter(trial_type == "test")%>%
  mutate(choiceAgent = ifelse( change == "false", agent, altAgent)) %>%
  mutate(trial = scale(as.numeric(trial), center = TRUE, scale=FALSE))

# maximal converging model
lm <- glmer(correct ~ change + (change |id) + (change || choiceAgent), 
              data = data_cg, family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(lm)
```

Conditions by trial.
```{r plot trials}
ms <- d %>%
  filter(trial_type == "test") %>%
  group_by(change, trial, id) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, 
       aes(x = trial, y = mean, col = change)) +
  geom_line(aes(group= change)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_hline(yintercept = 0.5, lty=2)+
  theme_few() + 
  scale_colour_solarized()
```

```{r plot agents}
ms <- d %>%
  filter(trial_type == "test") %>%
  mutate(choiceAgent = ifelse( change == "false", agent, altAgent)) %>%
  group_by(change, choiceAgent, id) %>%
  summarise(correct = mean(correct)) %>%
  multi_boot_standard(col = "correct")

ggplot(ms, 
       aes(x = choiceAgent, y = mean, col = change)) +
  geom_line(aes(group= change)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_hline(yintercept = 0.5, lty=2)+
  theme_few() + 
  scale_colour_solarized()
```





