---
title: "MCC Visualizations"
author: "Manuel Bohn"
date: "23 10 2018"
output: html_document
---

```{r setup, include=FALSE}
load("../saves/mcc_model_comparison.RData")

library(tidyverse)
library(knitr)
library(ggthemes)
library(langcog)
library(rwebppl)
library(matrixStats)
library(coda)
library(ggpubr)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```

```{r}
# data ex 1 and ex 2 adults

d1 <- bind_rows(read_csv(file="../data/novel.data.csv"),
               read_csv(file="../data/pref.data.csv")) %>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"),
         control = ifelse(change == TRUE, "true" , "false"))

d2 <- read_csv(file="../data/inf.data.csv") %>%
  mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"),
         control = ifelse(control == TRUE, "true" , "false"))

d <- bind_rows(d1,d2) %>%
  mutate(condition = ifelse(condition == "preference", 2, ifelse(condition == "novelty", 3,1)))


```

```{r}
# plot ex 1 and 2 adults

## pointrange plot
p1 <- d %>%
  filter(trial_type == "test") %>%
  mutate(control = ifelse(control == "true", "Control", "Test"),
         condition = factor(condition), 
         experiment = ifelse(condition == "1", "1","2"))%>%
  group_by(experiment,condition ,control, id) %>%
  summarise(correct = mean(correct))

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


exp1 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "1"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "1"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "1"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#657b83","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),
        panel.border = element_rect(color = "#dc322f", fill = NA, size = 6))


exp2 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "2"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "2"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "2"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
       axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))


exp3 <- ggplot() +
  geom_rect(data = p2%>%filter(condition == "3"), aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1%>%filter(condition == "3"), aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2%>%filter(condition == "3"), aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#dc322f","#268bd2","#268bd2"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))


 ggplot() +
  geom_rect(data = p2, aes(colour = experiment, size = 4), fill = NA, alpha = 1 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf, show.legend=FALSE)+
  geom_jitter(data = p1, aes(x = control, y = correct, col = control), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = control, y = mean, col = control,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Informativeness")))+
  theme_few() + 
  ylim(-0.05,1.05)+
  guides(alpha = F,size =F)+
  scale_color_manual(name = "Condition",
                     breaks=c("Test","Control"),
                     values= c("#dc322f","#268bd2","#839496","black"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),
        panel.border = element_blank()
        )



```



```{r}
ggarrange(exp1,exp2,exp3, ncol = 3, nrow = 1, legend = "right", common.legend = T)
```

```{r}
ggsave("graphs/ex1_2.png", width = 6.5, height = 2, scale = 1.8)
```



```{r}
# barplots
p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(condition ,control, id) %>%
  summarise(correct = mean(correct))  %>%
  multi_boot_standard(col = "correct")

ggplot(p1, 
       aes(x = control, y = mean, fill = control)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x="",y="Proportion Expected Choice")+
  facet_wrap( ~ condition, labeller = as_labeller(c(`2`="Exp. 2 - Preference", `3`="Exp. 2 - Novelty", `1`="Exp. 1 - Info."))) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_fill_solarized(name="Condition",
                     breaks=c("false", "true"),
                     labels=c("Test", "Control"))+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())


```

```{r}
ggsave("graphs/ex1_2.png", width = 6.5, height = 2, scale = 1.5)
```







```{r}
## kids preference data

d_ipad <- read_csv(file="kids_pref.data.csv")

d_hand_code <- read.csv(file="kids_pref_handcoding.data.csv", sep = ";")%>%
  mutate(age_num = as.numeric(as.character(age_num)))

d <- bind_rows(d_ipad,d_hand_code)%>%
  mutate(trial_type = ifelse(trial == "train", "train", "test"))%>%
  filter(subid != "200718_8_pref")


# check if someone needs to be excluded because wrong in training
# no one
d %>%
  filter(trial_type == "train") %>%
  group_by(subid)%>%
  summarise(correct = mean(correct)) %>%
  filter(correct == 0)
```

```{r}
# kids pref plot

p1 <- d %>%
  filter(trial_type == "test") %>%
  group_by(change,age, subid) %>%
  summarise(correct = mean(correct))%>%
  multi_boot_standard(col = "correct")


ggplot(p1, 
       aes(x = change, y = mean, fill = change)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x="",y="Proportion Expected Choice")+
  facet_wrap( ~ age, labeller = as_labeller(c(`2`="2-year-olds", `3`="3-year-olds", `4`="4-year-olds"))) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_fill_solarized(name="Condition",
                     breaks=c("false", "true"),
                     labels=c("Test", "Control"))





## pointrange plot
p1 <- d %>%
  filter(trial_type == "test") %>%
  mutate(change = ifelse(change == "true", "Control", "Test")) %>%
  group_by(age ,change, subid) %>%
  summarise(correct = mean(correct))

p2 <- p1 %>%
  multi_boot_standard(col = "correct") %>%
  ungroup()%>%
  mutate(age = as.character(age))

exp2k <- ggplot() +
  geom_rect(data = p2, aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1, aes(x = change, y = correct, col = change), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = change, y = mean,ymin = ci_lower, ymax = ci_upper, col = change),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Expected Choice")+
  facet_wrap( ~ age, labeller = as_labeller(c(`2`="2-year-olds", `3`="3-year-olds", `4`="4-year-olds"))) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F)+ 
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#268bd2","#268bd2","#268bd2"))+
  scale_color_manual(name="Condition",
                     breaks=c("Control","Test"),
                     values= c("#839496","black"))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.border = element_rect(color = "#268bd2", fill = NA, size = 6))



```


```{r}
ggarrange(exp12, exp2k, ncol = 1, nrow = 2, legend = "bottom", common.legend = T)
```



```{r}
ggsave("graphs/ex12_kids.pdf", width = 6.5, height = 4, scale = 1.5)
```




```{r}
# data ex 3 first round

dat <- bind_rows(read_csv(file="../data/ex3.novel.data.csv"),
               read_csv(file="../data/ex3.pref.data.csv")) %>%
  mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"))


# check if someone needs to be excluded because wrong in training
# no one, that's good
dat %>%
  filter(trial_type == "train") %>%
  group_by(id)%>%
  summarise(correct_inf = mean(correct_inf)) %>%
  filter(correct_inf == 0)
  
# check if someone did both experiments
# yes, two people
x <- dat %>%
  filter(trial_type == "train") %>%
  group_by(id)%>%
  summarise(n = length(correct_inf)) %>%
  filter(n > 2)

# exclude those who did both experiments
data <- dat %>%
  filter(!id %in% x$id) %>%
  filter(trial_type != "train") %>%
  mutate(Change = ifelse(change =="same", "Same speaker", "Different speaker"),
         Alignment = ifelse(alignment == "congruent", "Congruent", "Incongruent"),
         Experiment = ifelse(experiment == "pref_inf", "Preference", "Novelty"))


data %>%
  group_by(experiment,alignment,change) %>%
  summarise(n = length(id))


```


```{r}
# plot data Ex3 first round

p1 <- data %>%
  filter(trial_type == "test") %>%
  group_by(Experiment,Change ,Alignment, id) %>%
  summarise(correct = mean(correct_inf)) %>%
  multi_boot_standard(col = "correct")

ggplot(p1, 
       aes(x = Change, y = mean, fill = Alignment)) +
  geom_bar(stat="identity", position = position_dodge(), color = 'black') + 
  geom_hline(yintercept = 0.5, lty=2)+
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),position = position_dodge(width = 0.9))+
  labs(x=" ",y="Proportion Choosing More Informative")+
  facet_grid( ~ Experiment)+
  theme_few(base_size = 12) + 
  scale_fill_brewer(type = "qual")+
  theme(axis.text.x=element_text(angle = 0, vjust = 0.5, hjust = 0.5))+
  ylim(0,1)



## pointrange plot
p1 <- data %>%
  filter(trial_type == "test") %>%
  group_by(Experiment,Change ,Alignment, id) %>%
  summarise(correct = mean(correct_inf))

p2 <- p1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_rect(data = p2, aes(fill = NA), alpha = 0.4 ,xmin = -Inf,xmax = Inf, ymin = -Inf,ymax = Inf)+
  geom_jitter(data = p1, aes(x = Alignment, y = correct), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = p2, aes(x = Alignment, y = mean,ymin = ci_lower, ymax = ci_upper),size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Choosing More Informative")+
  facet_grid ( ~ Experiment + Change) +
  theme_few(base_size = 20) + 
  ylim(-0.05,1.05)+
  guides(alpha = F, fill = F, col = F)+ 
  scale_fill_manual(name="Condition",
                     breaks=c("1","2","3"),
                     values= c("#859900","#859900","#859900"))



pdata <- p1 %>%
  multi_boot_standard(col = "correct")%>%
  mutate(Model = "Data")



pmd <- bind_rows(pdata, plot.model%>%
                   filter(Model == "Noisy RSA Model")%>%
                   ungroup()%>%
                   mutate(Prior = "Strong",
                          Model = "RSA Model"))


ggplot() +
  geom_jitter(data = p1, aes(x = Alignment, y = correct), alpha = 0.2, width = .3,height = .025)+
  geom_pointrange(data = pmd, aes(x = Alignment, y = mean,col = Model, ymin = ci_lower, ymax = ci_upper),size = 1,  position = position_dodge(width = .5))+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Choosing More Informative")+
  facet_grid ( ~ Experiment + Change) +
  theme_few(base_size = 14) + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_color_manual(name="Condition",
                     breaks=c("Data","RSA Model"),
                     values= c("black","#859900"))+
  theme(axis.text.x=element_text(angle = 45, vjust = 1, hjust = 1))

```



```{r}
 ggsave("../graphs/Ex3_1_data_model_pred.pdf", width = 6.5, height = 3, scale = 1.3)
```




```{r}
## correlation round 1

pc1 <- plot.model%>%
  filter(Model == "Noisy RSA Model")%>%
  mutate(Prior = "Strong")
  
c1 <-ggplot(data = pc1,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = 1)+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = 1)+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = 1)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  #ggtitle("Experiment 3")+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = mean, y = Data), inherit.aes = F, size = 4)+
  #geom_smooth(method = "lm", se = F, col = "black", size =1)+
  theme_few(base_size = ) + 
  guides(col = F)+
  scale_colour_viridis_d()
```

```{r}
ggsave("../graphs/model_critique_ex3_round1.png", width = 3, height = 3, scale = 1)
```



```{r}
## correlation round 2

pc2 <- pred.ex3%>%
  filter(Model == "Noisy RSA Model")

c2 <- ggplot(data = pc2,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = 1)+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = 1 )+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = 1)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  ggtitle("Replication/Extension")+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.9, aes(x = mean, y = Data), inherit.aes = F, size = 6)+
  #geom_smooth(method = "lm", se = F, col = "black", size =0.4)+
  theme_few(base_size = 20) + 
  scale_colour_manual(values = rev(viridis::viridis(3)))
```

```{r}
ggarrange(c1, c2, ncol = 2, nrow = 1, legend = "right", common.legend = T)
```

```{r plotmodelcomp}

pc1 <- plot.model%>%
  filter(Model == "Noisy RSA Model")%>%
  mutate(Prior = "Strong")
  
c1 <-ggplot(data = pc1,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_point(size = 2)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = .5)+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = .5)+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = mean, y = Data), inherit.aes = F, size = 3)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  theme_few(base_size = 12) + 
  guides(col = F)+
  scale_colour_viridis_d()

pc2 <- pred.ex3%>%
  filter(Model == "Noisy RSA Model")

c2 <- ggplot(data = pc2,aes(x = mean, y = Data, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_point(size = 2)+
  geom_errorbar(aes(ymin = Data_ci_low, ymax = Data_ci_up),width = 0,size = .5 )+
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0,size = .5)+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = mean, y = Data), inherit.aes = F, size = 3)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  theme_few(base_size = 12) + 
  scale_colour_manual(values = rev(viridis::viridis(3)))

pc3 <- data.frame(
    ex3 = pc1%>%pull(Data),
    ex3_ci_l = pc1%>%pull(Data_ci_low),
    ex3_ci_u = pc1%>%pull(Data_ci_up),
    ex4 = pc2%>%filter(Prior == "Strong")%>%pull(Data),
    ex4_ci_l = pc2%>%filter(Prior == "Strong")%>%pull(Data_ci_low),
    ex4_ci_u = pc2%>%filter(Prior == "Strong")%>%pull(Data_ci_up),
    Prior = "Strong")

c3 <- ggplot(data = pc3,aes(x = ex3, y = ex4, col = Prior)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_point(size = 2)+
  geom_errorbar(aes(ymin = ex4_ci_l, ymax = ex4_ci_u),width = 0,size = .5 )+
  geom_errorbarh(aes(xmin = ex3_ci_l, xmax = ex3_ci_u), height = 0,size = .5)+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = ex3, y = ex4), inherit.aes = F, size = 3)+
  coord_fixed()+
  xlim(0,1)+ylim(0,1)+
  xlab("Data Experiment 3")+
  ylab("Data Experiment 4")+
  theme_few(base_size = 12)+ 
  scale_color_viridis_d()

ggarrange(c1, c2, c3, ncol = 3, nrow = 1, legend = "right", common.legend = T)
 
```

```{r}
ggsave("../graphs/overview_ex3_4.pdf", width = 10, height = 3, scale = 1)
```


# kids

```{r pretest data, include=FALSE}
pref_data <- bind_rows(read_csv(file="../data/kids_pref_data.csv")%>%filter(age != "2")%>%mutate(speakerChange = change),
                       read_csv(file="../data/kids_pref_2_data.csv"))%>%
  filter(trial != "train")%>%
  mutate(age_bin = factor(age),
         experiment = "preference_pretest",
         condition = ifelse(speakerChange == F | speakerChange == "false", "same_speaker", "different_speaker"),
         agent = ifelse( speakerChange == F | speakerChange == "false", agent, altAgent),
         minage = min(age_num))%>%
  select(experiment,subid,age_bin,age_num,trial,condition,agent,correct,minage)


inf_data <- bind_rows(
  read_csv(file="../data/kids_inf_data.csv"),
  read_csv(file="../data/kids_inf_2_data.csv"))%>%
  filter(subage != "2",
         trial != "filler1",
         trial != "filler2")%>%
  mutate(age_bin = factor(subage),
         experiment = "informativeness_pretest",
         condition = ifelse(control == "no", "test", "control"),
        minage = min(age_num))%>%
  select(experiment,subid,age_bin,age_num,trial,condition,agent,correct,minage)
  
pre_data <- bind_rows(pref_data,
                      inf_data)


ex3_data <- read_csv(file="../data/kids_ex3_data.csv")%>%
  filter(trial != "filler1",trial != "filler2")%>%
  mutate(binned_age=cut(age_num, breaks=seq.int(3, 5, 0.05), labels=seq.int(0, 1.95, 0.05)))
```



```{r pretest plot so, echo = F}

pre_so <- pre_data %>%
  filter(experiment == "informativeness_pretest")%>%
  group_by(age_num,subid)%>%
  summarise(correct = mean(correct))


ggplot(data = pre_so, aes(x = age_num, y = correct)) +
  geom_jitter(alpha = 1, height = 0.1, width = 0.1, col = "grey")+
  geom_smooth(method = "lm", se = T, col = "black",fill = "darkgreen", alpha = .4, size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few(base_size = 20) +
  #ggtitle("Informativeness data")+
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  coord_fixed(ratio = 2)+
  theme(panel.border = element_rect(color = "#dc322f", fill = NA, size = 6))
```



```{r}
ggsave("../graphs/kids_inf2.png", width = 3, height = 3, scale = 1.5)
```


```{r pretest plot prior, echo = F}

pre_prior <- pre_data %>%
  filter(experiment == "preference_pretest")%>%
  group_by(condition,age_num,subid)%>%
  summarise(correct = mean(correct))


ggplot(data = pre_prior, aes(x = age_num, y = correct, col = condition)) +
  geom_jitter(alpha = 0.5, height = 0.1, width = 0.1)+
  geom_smooth(aes(fill = condition),method = "lm", se = T, col = "black",  alpha = .5, size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few() +
  #ggtitle("Preference data")+
  ylim(0,1)+
  guides(alpha = F)+ 
  coord_fixed(ratio = 2)+
  scale_color_solarized()+
  scale_fill_solarized()+
  theme(panel.border = element_rect(color = "#268bd2", fill = NA, size = 6),legend.position="bottom")



```

```{r}
ggsave("../graphs/kids_pref.png", width = 3.5, height = 3.5, scale = 1.2)
```

```{r pretest plot prior, echo = F}


kids_novel_data <- read_csv(file="../data/kids_novel.data.round1.csv")%>%
  filter(age != 2)%>%
  mutate(condition = ifelse(change == F, "same_speaker", "different_speaker"))


p_kids_novel <- kids_novel_data %>%
  group_by(condition,age_num,subid)%>%
  summarise(correct = mean(correct))


ggplot(data = p_kids_novel, aes(x = age_num, y = correct, col = condition)) +
  geom_jitter(alpha = 0.5, height = 0.1, width = 0.1)+
  geom_smooth(aes(fill = condition),method = "lm", se = T, col = "black",  alpha = .5, size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few() +
  #ggtitle("Preference data")+
  ylim(0,1)+
  guides(alpha = F)+ 
  coord_fixed(ratio = 2)+
  scale_color_solarized()+
  scale_fill_solarized()+
  theme(panel.border = element_rect(color = "#268bd2", fill = NA, size = 6),legend.position="bottom")



```

```{r}
ggsave("../graphs/kids_novel.png", width = 3.5, height = 3.5, scale = 1.2)
```

### Model based speaker optimality by age 

```{r plot so model pred, echo = F}

plot_model_pred_so <- kids_model_pred_so%>%
  group_by(age_bin)%>%
  summarise(mean = mean(speakerOptimality),
            lci = hdi_lower(speakerOptimality),
            uci = hdi_upper(speakerOptimality))
  




ggplot(data = plot_model_pred_so) +
  geom_line(data = kids_model_pred_so,aes(age_bin, speakerOptimality, group = iteration), col = "grey", alpha = 0.3) +
  geom_ribbon(aes(x =age_bin, ymin = lci, ymax = uci), fill = "green", alpha = .2) +
  geom_line(aes(age_bin, mean), col = "black", size = 1, alpha = 1) + 
  scale_x_continuous(limits=c(0,2), name="age", breaks = c(0,0.5,1,1.5,2), labels = c(3.0,3.5,4.0,4.5,5)) +
  scale_y_continuous(limits=c(-4, 4), name="Speaker optimality")+
  geom_hline(yintercept = 0, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few(base_size = 20) +
  #ggtitle("Informativeness data")+
  ylim(-4,4)+
  guides(alpha = F)+ 
  coord_fixed(ratio = 1/4)+
  theme(panel.border = element_rect(color = "#dc322f", fill = NA, size = 6))

```


```{r}
ggsave("../graphs/kids_so_model.png", width = 3, height = 3, scale = 1.5)
```


```{r plot prior model pred, echo = F}
plot_model_pred_prior <- kids_model_pred_prior%>%
  group_by(age_bin,condition)%>%
  summarise(mean = mean(prop_preferred),
            lci = hdi_lower(prop_preferred),
            uci = hdi_upper(prop_preferred))


ggplot(data = p_kids_novel, aes(x = age_num, y = correct, col = condition)) +
  geom_jitter(alpha = 0.5, height = 0.1, width = 0.1)+
  geom_smooth(aes(fill = condition),method = "lm", se = T, col = "black",  alpha = .5, size = 1)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few(base_size = 20) +
  #ggtitle("Preference data")+
  ylim(0,1)+
  guides(alpha = F)+ 
  coord_fixed(ratio = 2)+
  scale_color_solarized()+
  scale_fill_solarized()+
  theme(panel.border = element_rect(color = "#268bd2", fill = NA, size = 6),legend.position="bottom")

  

ggplot(data = plot_model_pred_prior) +
  geom_line(data = kids_model_pred_prior,aes(age_bin, prop_preferred, group = paste(iteration,condition, sep= ""), col = condition), alpha = 0.05) +
  geom_ribbon(aes(x =age_bin, ymin = lci, ymax = uci, fill = condition), alpha = .5) +
  geom_line(aes(age_bin, mean, group = condition), col = "black", size = 1, alpha = 1) + 
  scale_x_continuous(limits=c(0,2), name="age", breaks = c(0,0.5,1,1.5,2), labels = c(3.0,3.5,4.0,4.5,5)) +
  scale_y_continuous(limits=c(-0.05,1.05), name="Proportion Expected Choice")+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="age",y="Proportion Expected Choice")+
  theme_few(base_size = 20) +
  guides(alpha = F)+ 
  coord_fixed(ratio = 2)+
  scale_color_solarized()+
  scale_fill_solarized()+
  theme(panel.border = element_rect(color = "#268bd2", fill = NA, size = 6),legend.position="bottom")


```

```{r}
ggsave("../graphs/kids_prior_model.png", width = 5, height = 4, scale = 1.5)
```

```{r}

prior_only_predictions_across <- readRDS("../saves/prior_only_predictions_across.rds")

prior_only_model_across <- prior_only_predictions_across %>%
  select(value) %>%
  map_df(bind_rows)%>%
  mutate(iteration = rep(1:4000,each = 40))%>%
  gather(condition, prop_informative, -iteration,-age_bin)%>%
  separate(condition, into = c("model", "Speaker", "Alignment"), sep="_")%>%
  mutate(Speaker = ifelse(Speaker == "diff", "different_speaker","same_speaker"),
         Alignment = ifelse(Alignment == "con", "congruent","incongruent"))



model_pred_across <- readRDS("../saves/kids_model_predictions_across.rds")

kids_model_pred_across <- model_pred_across%>%
  select(value) %>%
  map_df(bind_rows)%>%
  mutate(iteration = rep(1:3400,each = 40))%>%
  select(-diff_priorReg,-same_priorReg,-speakerOptimality,-so_slope,-so_int)%>%
  gather(condition, prop_informative, -iteration,-age_bin)%>%
  separate(condition, into = c("model", "Speaker", "Alignment"), sep="_")%>%
  mutate(Speaker = ifelse(Speaker == "diff", "different_speaker","same_speaker"),
         Alignment = ifelse(Alignment == "cong", "congruent","incongruent"))

kids_model_pred_so <- model_pred_across%>%
  select(value) %>%
  map_df(bind_rows)%>%
  mutate(iteration = rep(1:3400,each = 40))%>%
  select(so_slope,so_int,age_bin,iteration,speakerOptimality)


no_prior_pred_across <- bind_rows(
  kids_model_pred_so%>%mutate(model = "no prior",
                              Speaker = "same_speaker",
                              Alignment = "congruent"),
    kids_model_pred_so%>%mutate(model = "no prior",
                              Speaker = "different_speaker",
                              Alignment = "congruent"),
    kids_model_pred_so%>%mutate(model = "no prior",
                              Speaker = "same_speaker",
                              Alignment = "incongruent"),
    kids_model_pred_so%>%mutate(model = "no prior",
                              Speaker = "different_speaker",
                              Alignment = "incongruent")
  ) %>%
  mutate(prop_informative = plogis(so_int+so_slope*age_bin))


model_comp_mean_ci <- bind_rows(
kids_model_pred_across%>%mutate(model = "Pragmatic"), 
prior_only_model_across%>%mutate(model = "Prior Only"),
no_prior_pred_across%>%mutate(model = "No Prior")
)%>%
  group_by(model,age_bin,Speaker,Alignment)%>%
  summarise(mean = mean(prop_informative),
            lci = hdi_lower(prop_informative),
            uci = hdi_upper(prop_informative))



```
### All models predictions

```{r, include = F}
p_data <- ex3_data %>%
  filter(trial != "filler1",
         trial != "filler2")%>%
  mutate(age_bin = age_num - 3)%>%
  group_by(Speaker, Alignment ,age_bin, subid)

ggplot(model_comp_mean_ci)+
  #geom_jitter(data = p_data, aes(x = age_bin, y = correct_inf), width = .025,height = .025, alpha = .2)+
  geom_ribbon(aes(x =age_bin, ymin = lci, ymax = uci, fill = model), alpha = .4) +
  geom_line(aes(age_bin, mean, col = model), size = .5, alpha = 1, linetype = 2) + 
  geom_smooth(data = p_data, aes(x = age_bin, y = correct_inf), col = "black", size = 0.6, method = "glm", method.args = list(family = "binomial"),  se = T,  alpha = .5, size = .4)+
  #geom_hline(yintercept = 0.5, lty=2)+
  labs(y="Proportion More Informative")+
  scale_x_continuous(limits=c(0,2), name="age", breaks = c(0,0.5,1,1.5,2), labels = c(3.0,3.5,4.0,4.5,5)) +
  ylim(-0.05,1.05)+
  facet_grid(~Speaker+Alignment)+
  theme_few()+
  coord_fixed(ratio = 2)+
  scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2")
```

```{r, include = F}
ggsave("../graphs/kids_model_predictions.png", width = 10, height = 3, scale = 1)
```

### RSA model predictions

```{r, include = F}

model_comp_mean_ci_rsa <- bind_rows(
kids_model_pred_across%>%mutate(model = "Pragmatic"), 
prior_only_model_across%>%mutate(model = "Prior Only")%>%mutate(prop_informative = 5),
no_prior_pred_across%>%mutate(model = "No Prior")%>%mutate(prop_informative = 5)
)%>%
  group_by(model,age_bin,Speaker,Alignment)%>%
  summarise(mean = mean(prop_informative),
            lci = hdi_lower(prop_informative),
            uci = hdi_upper(prop_informative))


p_data <- ex3_data %>%
  filter(trial != "filler1",
         trial != "filler2")%>%
  mutate(age_bin = age_num - 3)%>%
  group_by(Speaker, Alignment ,age_bin, subid)


p_data_2 <- ex3_data %>%
  filter(trial != "filler1",
         trial != "filler2")%>%
  mutate(age_bin = age_num - 3)%>%
  group_by(Speaker, Alignment ,age_bin, subid)%>%
  summarise(correct_inf = mean(correct_inf))

ggplot(model_comp_mean_ci_rsa)+
  geom_jitter(data = p_data_2, aes(x = age_bin, y = correct_inf), width = .025,height = .025, alpha = .2)+
  geom_ribbon(aes(x =age_bin, ymin = lci, ymax = uci, fill = model), alpha = .4) +
  geom_line(aes(age_bin, mean, col = model), size = .5, alpha = 1, linetype = 2) + 
  geom_smooth(data = p_data, aes(x = age_bin, y = correct_inf), col = "black", size = 0.6, method = "glm", method.args = list(family = "binomial"),  se = T,  alpha = .5, size = .4)+
  #geom_hline(yintercept = 0.5, lty=2)+
  labs(y="Proportion More Informative")+
  scale_x_continuous(limits=c(0,2), name="age", breaks = c(0,0.5,1,1.5,2), labels = c(3.0,3.5,4.0,4.5,5)) +
  ylim(-0.05,1.05)+
  facet_grid(~Speaker+Alignment)+
  theme_few()+
  coord_fixed(ratio = 2)+
  scale_colour_brewer(palette = "Dark2")+
  scale_fill_brewer(palette = "Dark2")
```

```{r, include = F}
ggsave("../graphs/kids_data.png", width = 10, height = 3, scale = 1)
```

```{r}

data <- ex3_data %>%
  filter(trial != "filler1",
         trial != "filler2")%>%
  group_by(Speaker, Alignment ,subage) %>%
  summarize(k = sum(correct_inf), n = n())%>%
  ungroup() %>%
  mutate(a = 1 + k,
         b = 1 + n - k,
         Data_ci_lower  = qbeta(.025, a, b),
         Data_ci_upper = qbeta(.975, a, b),
         Data = (a-1)/(a+b-2))%>%
  select(-a,-b,-n,-k)

model <- kids_model_pred_across %>%
  mutate(subage = ifelse(age_bin<1,"3","4"))%>%
  group_by(model,Speaker,Alignment,subage)%>%
  summarise(Model = mean(prop_informative),
            Model_ci_lower =hdi_lower(prop_informative) ,
            Model_ci_upper = hdi_upper(prop_informative))
  

cor_plot <- model %>%
  ungroup()%>%
  mutate(Data = data$Data,
         Data_ci_lower = data$Data_ci_lower,
         Data_ci_upper  =data$Data_ci_upper,3)


ggplot(data = cor_plot,aes(x = Model, y = Data, col = subage)) +
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_point(size = 3)+
  geom_errorbar(aes(ymin = Data_ci_lower, ymax = Data_ci_upper),width = 0,size = .5)+
  geom_errorbarh(aes(xmin = Model_ci_lower, xmax = Model_ci_upper), height = 0,size = .5)+
  coord_fixed()+
  stat_cor(method = "pearson", label.x = 0.01, label.y = 0.99, aes(x = Model, y = Data), inherit.aes = F)+
  xlim(0,1)+ylim(0,1)+
  xlab("Model")+
  theme_few() + 
  scale_colour_solarized()


cor.test(cor_plot$Model,cor_plot$Data)
```

```{r}
ggsave("../graphs/model_critique_kids.png", width = 3, height = 2.5, scale = 1.3)
```

