---
title: "MCC Paper MEthods"
author: "Manuel Bohn"
output: 
  html_document:
  toc: true
  toc_float: true
  
---

```{r setup, include=FALSE}

# load packages and functions
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(ggthemes)
library(langcog)
library(rwebppl)
library(matrixStats)
library(coda)
library(ggpubr)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```


```{r}
# preparing datafiles (delete eventually)

# d <- read_csv(file="../../stats/data/inf.data.csv") %>%
#   mutate(trial_type = ifelse(trial == "train", "train", "test"),
#          trial = alltrial -2,
#          experiment = "adult_ex1",
#          condition = ifelse(control == TRUE, "control", "test") )%>%
#   filter(trial_type == "test")%>%
#   select(experiment, id,  trial,condition, agent, correct)
# 
# write_csv(d , path="../../stats/data/adult_ex1.csv")
# 
# d <- read_csv(file="../../stats/data/novel.data.csv") %>%
#   mutate(trial_type = ifelse(trial == "train", "train", "test"),
#          experiment = "adult_ex2_novelty",
#          speaker = ifelse(change == TRUE, "different_speaker" , "same_speaker"),
#          agent = ifelse( condition == "same_speaker", agent, altAgent))%>%
#   filter(trial != "train")%>%
#   select(experiment, id, trial,speaker, agent, correct)
# 
# write_csv(d , path="../../stats/data/adult_ex2_novelty.csv")
# 
# d <- read_csv(file="../../stats/data/pref.data.csv") %>%
#   mutate(trial_type = ifelse(trial == "train", "train", "test"),
#          experiment = "adult_ex2_preference",
#          speaker = ifelse(change == TRUE, "different_speaker" , "same_speaker"),
#          agent = ifelse( condition == "same_speaker", agent, altAgent))%>%
#   filter(trial != "train")%>%
#   select(experiment, id, trial,speaker, agent, correct)
# 
# write_csv(d , path="../../stats/data/adult_ex2_preference.csv")
# 
# d <- bind_rows(read_csv(file="../../stats/data/ex3.novel.data.csv"),
#                read_csv(file="../../stats/data/ex3.pref.data.csv")) %>%
#   mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"),
#          agent = ifelse( change == "same", agent, altAgent),
#          common_ground_manipulation = ifelse(experiment == "novel_inf","novelty", "preference"),
#          experiment = "adult_ex3",
#          trial = alltrial -2,
#          speaker = ifelse(change == "same", "same_speaker", "different_speaker"))%>%
#   filter(trial_type == "test")%>%
#   select(experiment, id,trial, common_ground_manipulation, speaker ,alignment, agent, correct_inf)
# 
# write_csv(d , path="../../stats/data/adult_ex3.csv")
# 
# 
# d <- bind_rows(read_csv(file="../../stats/data/ex3.2.novel.strong.data.csv"),
#                read_csv(file="../../stats/data/ex3.2.novel.medium.data.csv"),
#                read_csv(file="../../stats/data/ex3.2.novel.weak.data.csv"),
#                read_csv(file="../../stats/data/ex3.2.pref.strong.data.csv"),
#                read_csv(file="../../stats/data/ex3.2.pref.medium.data.csv")
#                ) %>%
#   mutate(trial_type = ifelse(trial == "train1" | trial =="train2", "train", "test"),
#          agent = ifelse( change == "same", agent, altAgent),
#          common_ground_manipulation = ifelse(grepl("novel",experiment),"novelty", "preference"),
#          trial = alltrial -2,
#          speaker = ifelse(change == "same", "same_speaker", "different_speaker"),
#          prior_manipulation = prior,
#          experiment = "adult_ex4")%>%
#   filter(trial_type == "test")%>%
#   select(experiment, id,trial, common_ground_manipulation, prior_manipulation, speaker, alignment, agent, correct_inf)
# 
# write_csv(d , path="../../stats/data/adult_ex4.csv")
#
# 
# d <- bind_rows(read_csv(file="../../stats/data/kids_pref_data.csv")%>%filter(age != "2")%>%mutate(speakerChange = change),
#                        read_csv(file="../../stats/data/kids_pref_2_data.csv"))%>%
#   filter(trial != "train")%>%
#   mutate(age_bin = factor(age),
#          experiment = "child_ex2",
#          condition = ifelse(speakerChange == F, "same_speaker", "different_speaker"),
#          agent = ifelse( speakerChange == F, agent, altAgent),
#          id = subid,
#          minage = min(age_num))%>%
#   filter(trial != "train")%>%
#   select(experiment,id,age_bin,age_num,minage,trial,condition,agent,correct)
# 
# write_csv(d , path="../../stats/data/child_ex2.csv")
# 
# d <- bind_rows(
#   read_csv(file="../../stats/data/kids_inf_data.csv"),
#   read_csv(file="../../stats/data/kids_inf_2_data.csv"))%>%
#   filter(subage != "2",
#          trial != "filler1",
#          trial != "filler2")%>%
#   mutate(age_bin = factor(subage),
#          experiment = "child_ex1",
#          id =subid,
#          minage = min(age_num))%>%
#   select(experiment,id,age_bin,age_num,minage,trial,correct)
# 
# write_csv(d , path="../../stats/data/child_ex1.csv")
# 
# 
# d <- read_csv(file="../../stats/data/kids_ex3_data.csv")%>%
#   mutate(experiment = "child_ex3",
#          id = subid,
#          age_bin = subage,
#          speaker = Speaker,
#          alignment = Alignment,
#          minage = min(age_num))%>%
#   filter(trial != "filler1",trial != "filler2")%>%
#   select(experiment, id,age_bin,age_num,minage,trial, speaker, alignment, agent, correct_inf)
# 
#  write_csv(d , path="../../stats/data/child_ex3.csv")


```


```{r data, include= FALSE}
# load data files

# adults exp 1 
adult_ex1_data <- read_csv(file="../../stats/data/adult_ex1.csv")
# adults exp 2 novelty
adult_ex2_novelty_data <- read_csv(file="../../stats/data/adult_ex2_novelty.csv")
# adults exp 2 preference
adult_ex2_preference_data <- read_csv(file="../../stats/data/adult_ex2_preference.csv")
# adults ex3
adult_ex3_data <-read_csv(file="../../stats/data/adult_ex3.csv") 
# adults ex4
adult_ex4_data <-read_csv(file="../../stats/data/adult_ex4.csv") 

# children ex1
child_ex1_data <-read_csv(file="../../stats/data/child_ex1.csv")
# children ex2 preference
child_ex2_data <-read_csv(file="../../stats/data/child_ex2.csv") 
# children ex3
child_ex3_data <-read_csv(file="../../stats/data/child_ex3.csv") 

# model predictions adults ex3
ex3_model_predictions <- readRDS("../../stats/saves/ex3_model_predictions.rds")
# model comparison adults ex3
ex3_model_comparison <- readRDS("../../stats/saves/ex3_model_comparison.rds")
# model predictions adults ex4
ex4_model_predictions <- readRDS("../../stats/saves/ex4_model_predictions.rds")
# model comparison adults ex4
ex4_model_comparison <- readRDS("../../stats/saves/ex4_model_comparison.rds")
```

# Adults 
## Experiment 1

```{r, figure 1}

p_fig1 <- bind_rows(adult_ex1_data,
                    adult_ex2_novelty_data %>%
                      mutate(condition = ifelse(condition == "same_speaker","test", "control")),
                    adult_ex2_preference_data%>% 
                      mutate(condition = ifelse(condition == "same_speaker","test", "control"))) %>%
  mutate(experiment = factor(experiment),
         condition = factor(condition, levels = c("test","control")))%>%
  group_by(experiment,condition , id) %>%
  summarise(correct = mean(correct))

p_fig1x <- p_fig1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = p_fig1, aes(x = condition, y = correct, col = condition), alpha = 0.3, width = .3,height = .02)+
  geom_pointrange(data = p_fig1x, aes(x = condition, y = mean, col = condition,ymin = ci_lower, ymax = ci_upper),size = .8, pch = 5, fatten = 2.5)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Correct")+
  facet_wrap( ~ experiment, labeller = as_labeller(c(`adult_ex2_preference`="Exp. 2 - Pref.", `adult_ex2_novelty`="Exp. 2 - Nov.", `adult_ex1`="Exp. 1")))+
  theme_few() + 
  ylim(-0.05,1.05)+
  guides(alpha = F,size =F)+
  scale_color_solarized(name = "Condition",
                     breaks=c("test","control"))+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())


```

```{r, figure x}

p_figx <- bind_rows(child_ex1_data%>%
                      mutate(condition = "test"),
                    child_ex2_data %>%
                      mutate(condition = ifelse(condition == "same_speaker","test", "control"))) %>%
  mutate(experiment = factor(experiment),
         condition = factor(condition, levels = c("test","control")))%>%
  group_by(experiment,condition,age_num, id) %>%
  summarise(correct = mean(correct))


ggplot(data = p_figx, aes(x = age_num, y = correct, col = condition)) +
  geom_jitter(alpha = 0.5, height = 0.02, width = 0)+
  geom_smooth(aes(fill = condition),method = "lm", se = T, alpha = .5, size = .7)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="Age",y="Proportion Correct")+
  facet_wrap( ~ experiment, labeller = as_labeller(c(`child_ex2`="Exp. 2", `child_ex1`="Exp. 1")))+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  scale_color_solarized(name = "Condition")+
  scale_fill_solarized(name = "Condition")

```
```{r, fig.height=3, fig.width=8}
#ggarrange(fig1_a, fig1_c, ncol = 2, nrow = 1, common.legend = F, legend = "bottom", widths = c(1,1.2))
```

